version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensor_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
    depends_on:
      - influxdb
    restart: unless-stopped

  data-producer:
    build:
      context: ./data-producer
    depends_on:
      - mosquitto
    restart: unless-stopped

  data-consumer:
    build:
      context: ./data-consumer
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

volumes:
  mosquitto-data:
  influxdb-data:
  grafana-data:

